[profile.default]
src = 'contracts'
test = 'test/foundry'
script = 'script'
out = 'out'
libs = ['lib']
remappings = []
optimizer = true
optimizer-runs = 10_000
solc-version = "0.4.24"

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"
avalanche = "${RPC_AVALANCHE}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
gnosis = "${RPC_GNOSIS}"
chiado = "${RPC_CHIADO}"

[etherscan]
mainnet={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=1}
optimism={key="${ETHERSCAN_API_KEY_OPTIMISM}",chainId=10}
avalanche={key="${ETHERSCAN_API_KEY_AVALANCHE}",chainId=43114}
polygon={key="${ETHERSCAN_API_KEY_POLYGON}",chainId=137}
arbitrum={key="${ETHERSCAN_API_KEY_ARBITRUM}",chainId=42161}
fantom={key="${ETHERSCAN_API_KEY_FANTOM}",chainId=250}
gnosis={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=100}
chiado={key="${ETHERSCAN_API_KEY_GNOSIS}",chainId=10200}
goerli={key="${ETHERSCAN_API_KEY_MAINNET}",chainId=5}

[fuzz]
runs=1000

# See more config options https://github.com/gakonst/foundry/tree/master/config
